{"name":"SDO_DAS_Relational.applyChanges","purpose":"Applies the changes made to a data graph back to the database.","manualid":"function.sdo-das-relational-applychanges","version":false,"params":[{"name":"database_handle","type":"PDO","optional":"false"},{"name":"root_data_object","type":"SDODataObject","optional":"false"}],"return":{"type":"void","description":"None.\n   Note however that the datagraph that was passed is still intact and usable.\n   Furthermore, if data objects were created and written back to a \n   table with autogenerated primary keys, \n   then those primary keys will now be set in the data objects.\n   If the changes were successfully written, \n   then the change summary associated with the datagraph will \n   have been cleared, \n   so that it is possible to now make further changes to the \n   data graph and apply those changes in turn.\n   In this way it is possible to work with the same data graph \n   and apply changes repeatedly."},"errors":"SDO_DAS_Relational::applyChanges\n   can throw an SDO_DAS_Relational_Exception if it is \n   unable to apply all the changes correctly.The Relational DAS starts a database transaction before \n   beginning to apply the changes and will commit \n   the transaction only if they are all successful.\n   The Relational DAS generates qualified update and delete statements \n   which contain a where clause that specifies that the row to be \n   updated or deleted must contain the same values that it did \n   when the data was first retrieved.\n   This is how the optimistic concurrency is implemented.\n   If any of the qualified update or delete statements fails to update or \n   delete their target row, it may be because the data has been altered \n   in the database in the meantime.\n   In any event, if any update fails for any reason, \n   the transaction is rolled back and an exception thrown.\n   The exception will contain the generated SQL statement that failed.The Relational DAS also catches any PDO exceptions and obtains PDO \n   diagnostic information which it includes in an \n   SDO_DAS_Relational_Exception which it then throws.","notes":[],"changelog":[],"seealso":[]}